config/routes.rb
Tweeporter::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  get "events/index"

  get "home/index"

  get "events/add"
  
  get "confirmation/index"

  match 'locations/:country', to: 'locations#bycountry'

  resources :locations

	default_url_options :host => "localhost:3000"

  #resources :events 
  resources :events do
    resources :comments, :only => [:create]
  end
  root to: "events#index"
 
  

  resources :events do
    member do 
        post 'create'
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :events
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locs = Location.select(:country).map(&:country).uniq
		@locs.sort_by!{ |char| char.downcase }

		@ev = Event.all
		@locations=Location.all
		@hash = Gmaps4rails.build_markers(@locations) do |location, marker|
  			marker.lat location.latitude
  			marker.lng location.longitude
  			@x = Event.where(:location_id => location.id)
  			if @x.count > 0 then
	  			heading = @x.count > 1 ? "Latest of #{@x.count} events from #{location.name}:" : "One event reported in #{location.name}:"
	  			photo = ""
	  			if @x.last.photos.first!=nil
	  				photo="<img src='#{@x.last.photos.first.thumbnail}' alt='#{@x.last.photos.first.user}' />"	
				end
	  			box=[heading, 
	  				"<strong>#{@x.last.title}</strong>", 
	  				photo,
	  				"<a href='/events/#{@x.last.id}'>view this event &raquo;</a>"].join("\n")
	  			marker.infowindow box.gsub(/\n/, '<br />')
	  			marker.title @x.last.title
	  		end
  		end
	end

	def bycountry
		@locs = Location.where('lower(country) = ?', params[:country].downcase)		
		@events = []
		@locs.each do |l|
			Event.where(:location_id => l.id).each do |e|
				@events << e
			end
		end
		@events.reverse!
	end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_menu.html.erb
<ul class="nav navbar-nav">
	<% locs = Location.select(:country).map(&:country).uniq.sort_by!{ |char| char.downcase } %>
	<% locs[0...4].collect do |c| %>
		<li><%= link_to c, "/locations/#{c.downcase}" %> </li>
	<% end %>
	<% if locs.count > 4 then %>
		<li><%= link_to "All Countries", locations_path %></li>
	<% end %>
</ul>

app/views/locations/bycountry.html.erb
<h1>Events from <%= @locs.first.country %></h1>
<%= render 'events/evlist' %>

app/views/locations/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="reportevent">
<h1>Countries</h1>
To date, events have been reported from these countries. Select a country to see what is going on there!

<div class="list-group">
<% @locs.each do |c| %> 
 <%= link_to "#{c}  <span class='badge'> #{Location.where(:country => c).count} </span>".html_safe, "/locations/#{c.downcase}", :class => "list-group-item" %> 
<% end %>
</div>
</div>
<div style='width: 80%; margin: 0 auto;'>
<a name="map"> </a>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>